name       : cmocka
version    : 1.1.5
release    : 2
source     :
    - https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz : f0ccd8242d55e2fd74b16ba518359151f6f8383ff8aef4976e48393f77bba8b6
license    : Apache-2.0
component  : programming.library
summary    : An elegant unit testing framework for C with support for mock objects.
description: |
    An elegant unit testing framework for C with support for mock objects.
setup      : |
    mkdir build
    pushd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DUNIT_TESTING=ON ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
    #rm $installdir/usr/lib/*.a
check      : |
    pushd build
    %make test
    popd
